name: Processing issues
on: 
  issues:
    types: [opened]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:   
  fastlane-env:
    permissions:
      contents: read # to fetch code (actions/checkout)
      issues: write # to comment on issues

    name: fastlane env reminder
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: fastlane/github-actions/fastlane-env-reminder@latest
      with:
        repo-token: "${{ secrets.BOT_GITHUB_TOKEN }}"
